### ISSUE TITLE
Choose a CSS Framework BESIDES BOOTSTRAP

### ISSUE THREAD

**Issue by EmilyNecciai** [SBerkebile7/project-1#2]
Spencer investigating https://get.foundation/index.html

But open to other options

**Comment by SBerkebile7** [comment]
Okay, changed my mind on Foundation - it is extremely thorough which also makes it very complicated. As another bit of confusion, we'd need to use Syntactically Awesome Style Sheets (SASS) to use critical features like flex-box so I think it'd be best to pass on this.

I did find another potential option: https://tailwindcss.com/

This seems like it'll be a good option instead as it's a bit more straight forward and I am currently watching this video to get some insight on it: https://www.youtube.com/watch?v=UBOj6rqRUME
