### ISSUE TITLE
List your strengths so far to help with the assignment of work.

### ISSUE THREAD

**Issue by EmilyNecciai** [SBerkebile7/project-1#3]
Please list your strengths in the comments below.

**Comment by EmilyNecciai** [comment]
@jeevanthapa1987 @raevindunson @SBerkebile7 Please list/rank your strengths in the comments below so we can start discussing who will handle which pieces of the project? Thanks!

**Comment by EmilyNecciai** [comment]
So far, I feel the most confident about CSS, HTML, and CSS Frameworks. I'm also pretty decent with jquery. Javascript is fine, and so is DOM manipulation but I seem to have some trouble with getting them to work quickly.

I also have experience in UX design, so I can help with mockups. I have a lot of experience with Git, so I'm available to help with those problems.

**Comment by SBerkebile7** [comment]
Good morning, all! I'd say my strengths are probably based in jQuery and JavaScript. Those portions of the assignments I've done so far have made the most sense to me, and I have zero eye for design. I can always aid, but when it comes to layout and making it look nice I am definitely lacking there.

**Comment by jeevanthapa1987** [comment]
I need to know a lot of thing.I am preety week in javascript i know little about css.

**Comment by raevindunson** [comment]
Hello,
I think my strengths are in HTML and CSS, but I am slowly getting better
with JavaScript.
